# Generated by Django 5.1.7 on 2025-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('id_session', models.CharField(max_length=100)),
                ('duracion_minutos', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('permiso_ep', models.IntegerField()),
                ('id_empresa', models.IntegerField()),
                ('id_puesto', models.IntegerField()),
                ('minutos_monitoreo_anterior', models.IntegerField()),
                ('minutos_monitoreo_posterior', models.IntegerField()),
            ],
        ),
    ]
