# Generated by Django 5.1.7 on 2025-04-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='SessionTechra',
        ),
    ]
