# Generated by Django 5.1.7 on 2025-04-08 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_rename_session_sessiontechra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontechra',
            name='UID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
