# Generated by Django 5.1.7 on 2025-04-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=255)),
            ],
        ),
    ]
