# Generated by Django 5.1.7 on 2025-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.IntegerField(blank=True, null=True)),
                ('diagnostico_sol', models.CharField(blank=True, max_length=255, null=True)),
                ('no_parte_componente', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_componente', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Refacciones',
            },
        ),
    ]
