from django.db import models

# Create your models here.
class Ticket(models.Model):

    ticket = models.IntegerField()
    titulo = models.CharField(max_length=100)
    fecha_creacion = models.DateField()
    prioridad = models.CharField(max_length=100)
    zona = models.CharField(max_length=100)
    tecnico = models.CharField(max_length=100)
    area_atencion = models.CharField(max_length=100)
    serie = models.CharField(max_length=100)
    clave_cliente = models.IntegerField()
    cliente = models.CharField(max_length=100)
    localidad = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255)
    contacto_1_nombre = models.CharField(max_length=100)
    contacto_1_email = models.CharField(max_length=100)
    contacto_1_telefono = models.CharField(max_length=100)
    contacto_2_nombre = models.CharField(max_length=100)
    contacto_2_email = models.CharField(max_length=100)
    contacto_2_telefono = models.CharField(max_length=100)
    latitud = models.CharField(max_length=100)
    longitud = models.CharField(max_length=100)
    distancia = models.IntegerField()
    fecha_nota = models.DateTimeField()
    id_tipo_prioridad = models.IntegerField()
    tipo_prioridad = models.CharField(max_length=100)
    id_color = models.IntegerField()
    color = models.CharField(max_length=100)
    minutos_alertamiento = models.IntegerField()
    id_puesto_escalamiento = models.IntegerField()
    mensaje_alerta = models.CharField(max_length=100)
    alertar_despues_fecha = models.DateTimeField()
    estatus_nota_alertamiento = models.CharField(max_length=100)
    tiempo_duracion = models.CharField(max_length=100)
    unidad_medida_duracion = models.CharField(max_length=100)
    fecha_hora_inicio = models.DateTimeField()
    check_in = models.CharField(max_length=100)
    check_out = models.CharField(max_length=100)
    check_in_programado = models.CharField(max_length=100)
    check_out_programado = models.CharField(max_length=100)
    id_ultimo_estado = models.IntegerField()


