# Generated by Django 5.1.7 on 2025-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_area_atencion_alter_ticket_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='alertar_despues_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_hora_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_puesto_escalamiento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_tipo_prioridad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_ultimo_estado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='minutos_alertamiento',
            field=models.IntegerField(null=True),
        ),
    ]
