# Generated by Django 5.1.7 on 2025-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_alertar_despues_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='clave_cliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='distancia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_color',
            field=models.IntegerField(null=True),
        ),
    ]
