# Generated by Django 5.1.7 on 2025-04-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_clave_cliente_alter_ticket_distancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
